spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094

producer.domain.enabled: false
producer.simple.enabled: false
producer.visual.enabled: true

kafka:
  topic:
    simple: simpleTopicName
    domain: domainTopicName
    visual: visualTopicName
  producer:
    sendRate:
      simple: 1000
      domain: 1000
      visual: 1000