spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
consumer:
  visual:
    enabled: true
  domain:
    enabled: false
  simple:
    enabled: false

kafka:
  topic:
    simple: simpleTopicName
    domain: domainTopicName
    visual: visualTopicName
  groupId:
    simple: simple
    domain: domain
    visual: visual